---
- name: Create Kubernetes config directory
  file:
    path: "/home/{{ kubeadm.os_user.user }}/.kube/"
    owner: "{{ kubeadm.os_user.user }}"
    group: "{{ kubeadm.os_user.group }}"
    mode: '0755'
    state: directory
  become: yes

- name: Copy admin.conf to Home directory
  copy:
    src: "{{ role_path }}/files/kubeadm_admin.conf"
    dest: "/home/{{ kubeadm.os_user.user }}/.kube/admin.conf"
    owner: "{{ kubeadm.os_user.user }}"
    group: "{{ kubeadm.os_user.group }}"
    mode: '0755'
  become: yes

- name: Update .profile
  lineinfile:
    dest: "/home/{{ kubeadm.os_user.user }}/.profile"
    line: 'export KUBECONFIG=/home/{{ kubeadm.os_user.user }}/.kube/admin.conf'
    regexp: '^export KUBECONFIG=' 
    insertafter: "EOF"
    state: present
  become: yes