---
- name: Shut down existing kubernetes-cluster (node)
  shell: 
    cmd: "/usr/bin/kubeadm reset --force"
    removes: "/etc/kubernetes/kubelet.conf"
  become: yes
  when:
    - k8s_node is defined
    - k8s_node in [ "become_master", "node" ]

- name: Shut down existing kubernetes-cluster (master)
  shell: 
    cmd: "/usr/bin/kubeadm reset --force"
    removes: "/etc/kubernetes/admin.conf"
  become: yes
  when:
    - k8s_node is defined
    - k8s_node == "install_master"

- name: Remove bash-completion /etc/bash_completion.d/kubectl
  file:
    path: "/etc/bash_completion.d/kubectl"
    state: absent
  become: yes
