---
- name: Register Kubernetes-Token
  shell:
    cmd: "kubeadm token list | tail -1 | cut -f 1 -d \" \""
  changed_when: false
  run_once: true
  register: token
  become: yes
  when:
    - k8s_node is defined
    - k8s_node == "install_master"

- name: Register Kubernetes SHA-Hash
  shell:
    cmd: "openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'"
  changed_when: false
  run_once: true
  register: sha_hash
  become: yes
  when:
    - k8s_node is defined
    - k8s_node == "install_master"

- name: Store Kubernetes Token and SHA-Hash
  set_fact: 
    kubeadm_token: "{{ token.stdout | regex_replace('\n', '') }}"
    kubeadm_sha_hash: "{{ sha_hash.stdout | regex_replace('\n', '') }}"
  run_once: true
  become: yes
  when:
    - k8s_node is defined
    - k8s_node == "install_master"

- name: Save Kubernetes Token to dynamic_vars/kubernetes.yml
  lineinfile:
    dest: "{{ inventory_dir }}/dynamic_vars/group/kubernetes.yml"
    line: '_kubeadm_token: "{{ kubeadm_token }}"'
    insertafter: "EOF"
    regexp: '^_kubeadm_token: ' 
    state: present
  run_once: true
  delegate_to: localhost
  become: no
  when:
    - k8s_node is defined
    - k8s_node == "install_master"

- name: Save Kubernetes SHA-Hash  to dynamic_vars/kubernetes.yml
  lineinfile:
    dest: "{{ inventory_dir }}/dynamic_vars/group/kubernetes.yml"
    line: '_kubeadm_sha_hash: "{{ kubeadm_sha_hash }}"'
    insertafter: "EOF"
    regexp: '^_kubeadm_sha_hash: '
    state: present
  run_once: true
  delegate_to: localhost
  become: no
  when:
    - k8s_node is defined
    - k8s_node == "install_master"

- name: Join to Kubernetes cluster
  shell: 
    cmd: "kubeadm join --token {{ kubeadm_token }} --discovery-token-ca-cert-hash sha256:{{ kubeadm_sha_hash }} {{ master_serveNet_ip }}:6443"
    creates: "/etc/kubernetes/kubelet.conf"
  become: yes
  when:
    - k8s_node is defined
    - k8s_node in [ "become_master", "node" ]