---
- name: Cleanup k8s
  include_tasks: k8s-cleanup.yml
  tags: [ never, cleanup ]

- name: Cleanup other kubernetes-engines
  include_role:
    name: "{{ item }}"
    apply:
      tags:
        - cleanup
  with_items:
    - kube_02_install_k3s
    - kube_02_install_minikube
    - kube_02_install_rke
  tags: [ nocleanup ]
    

- name: Create kubernetes-user
  include_tasks: k8s-create_user.yml
  when: 
    - k8s_node is defined
    - serveNet_ip is defined
    - k8s_node in [ "install_master", "become_master", "node" ]
    - kubernetes_engine == "kubeadm"

- name: Setup kubeadm-master
  include_tasks: k8s-master.yml
  when: 
    - k8s_node is defined
    - serveNet_ip is defined
    - k8s_node == "install_master"
    - kubernetes_engine == "kubeadm"

- name: Setup kubeadm-node
  include_tasks: k8s-node.yml
  when: 
    - k8s_node is defined
    - serveNet_ip is defined
    - k8s_node in [ "install_master", "become_master", "node" ]
    - kubernetes_engine == "kubeadm"

- name: Setup kubernetes-user
  include_tasks: k8s-user_setup.yml
  when: 
    - k8s_node is defined
    - serveNet_ip is defined
    - k8s_node in [ "install_master", "become_master", "node" ]
    - kubernetes_engine == "kubeadm"